// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GameGUI_h
#define GameGUI_h
#include <FL/Fl.H>
void GenerateNewBoard(const int& height, const int& width, const int& mineCount);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *customGameWindow;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *heightInputBox;
extern Fl_Value_Input *widthInputBox;
#include <FL/Fl_Input_Choice.H>
extern Fl_Input_Choice *generateTypeSwitch;
extern Fl_Value_Input *mineCountBox;
extern Fl_Value_Input *mineChanceBox;
#include <FL/Fl_Button.H>
extern Fl_Button *okButton;
extern Fl_Button *cancelButton;
Fl_Double_Window* MakeCustomBoardWindow();
extern Fl_Menu_Item menu_generateTypeSwitch[];
#define specificMineCount (menu_generateTypeSwitch+0)
#define specificSpawnChance (menu_generateTypeSwitch+1)
extern Fl_Double_Window *mainWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *menuBar;
#include <FL/Fl_Group.H>
extern Fl_Group *gameArea;
extern Fl_Menu_Item menu_menuBar[];
#define newGameMenu (menu_menuBar+0)
#define customGameOption (menu_menuBar+1)
#endif
